version: '3.8'
services:
  d-wallet-api:
    image: asia.gcr.io/blockchain-289901/d-wallet-api:latest
    container_name: d-wallet-api
    environment:
      - NODE_ENV=${NODE_ENV}
      - NODE_APP_INSTANCE=${NODE_APP_INSTANCE}
    restart: always
    ports:
      - "8080:8080"