version: '3.8'
services:
  d-wallet-db-dev:
    image: mongo:5.0.2-focal
    container_name: d-wallet-db-dev
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./mongo-init-dev.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./data-dev:/data/db
    ports:
      - '26000:27017'